import { useCallback, useEffect, useState } from 'react';
import { Alert, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { fileAccessUrl, listFiles, loadServerUrl } from '@/src/services/api';

export default function FilesScreen(){
  const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const data=await listFiles(await loadServerUrl());setItems(Array.isArray(data)?data:(data?.items??data?.files??[]))}catch{Alert.alert('加载失败','请确认已经登录。')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const open=async(item:any,download:boolean)=>{try{const history=String(item.history_id??item.id);const index=String(item.file_index??item.index??0);await Linking.openURL(await fileAccessUrl(await loadServerUrl(),history,index,download))}catch{Alert.alert('打开失败')}};
  return <ScrollView style={s.page} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>{void load()}}/>}><Text style={s.title}>文件</Text>{items.length===0?<Text style={s.empty}>{loading?'加载中...':'暂无文件'}</Text>:items.map((item,i)=><View key={String(item.id??`${item.history_id}-${i}`)} style={s.card}><Text style={s.cardTitle} numberOfLines={2}>{item.title??item.filename??item.name??'未命名文件'}</Text><Text style={s.filename} numberOfLines={1}>{item.filename??item.path??''}</Text><View style={s.meta}><Text>{item.platform??''} · {item.type??item.media_type??''}</Text><Text>{item.size_human??item.file_size_human??''}</Text></View><View style={s.actions}><Pressable onPress={()=>{void open(item,false)}}><Text style={s.action}>预览</Text></Pressable><Pressable onPress={()=>{void open(item,true)}}><Text style={s.action}>下载</Text></Pressable></View></View>)}</ScrollView>
}
const s=StyleSheet.create({page:{flex:1,padding:20,backgroundColor:'#f5f7fb'},title:{fontSize:34,fontWeight:'800',color:'#111827',marginTop:8},empty:{textAlign:'center',marginTop:100,color:'#657187'},card:{backgroundColor:'#fff',padding:16,borderRadius:8,marginTop:12},cardTitle:{fontSize:17,fontWeight:'800',color:'#172033'},filename:{fontSize:13,color:'#8a95a5',marginTop:5},meta:{flexDirection:'row',justifyContent:'space-between',marginTop:10,color:'#657187'},actions:{flexDirection:'row',justifyContent:'space-between',marginTop:14},action:{color:'#1671e8',fontWeight:'700',fontSize:15}});
