import { Alert, Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { useEffect, useState } from 'react';
import { loadServerUrl, saveServerUrl } from '@/src/services/api';
export default function SettingsScreen(){
  const [server,setServer]=useState('');
  const [wifi,setWifi]=useState(true);
  useEffect(()=>{ let active=true; void loadServerUrl().then(value=>{if(active)setServer(value)}); return ()=>{active=false}; },[]);
  const save=async()=>{await saveServerUrl(server); Alert.alert('已保存','服务端地址已更新。')};
  return <View style={styles.page}><Text style={styles.title}>设置</Text><Text style={styles.muted}>配置下载服务和本地偏好</Text><View style={styles.group}><Text style={styles.label}>服务端地址</Text><TextInput value={server} onChangeText={setServer} placeholder="https://your-server.example" placeholderTextColor="#8a95a5" autoCapitalize="none" autoCorrect={false} keyboardType="url" style={styles.input}/><Text style={styles.hint}>保存后用于提交和查看下载任务</Text></View><View style={styles.row}><View><Text style={styles.rowTitle}>仅 Wi-Fi 下载</Text><Text style={styles.hint}>移动网络下暂停任务</Text></View><Switch value={wifi} onValueChange={setWifi} trackColor={{true:'#9fc2ff'}} thumbColor={wifi?'#2f7df6':'#f4f5f7'}/></View><Pressable style={styles.save} onPress={()=>{void save()}}><Text style={styles.saveText}>保存设置</Text></Pressable></View>}
const styles=StyleSheet.create({page:{flex:1,padding:24,backgroundColor:'#f7f9fc'},title:{fontSize:28,fontWeight:'800',color:'#172033'},muted:{fontSize:15,color:'#657187',marginTop:8},group:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5eaf2',borderRadius:10,padding:16,marginTop:26},label:{fontSize:14,fontWeight:'700',color:'#344054'},input:{height:48,borderWidth:1,borderColor:'#d8dfeb',borderRadius:8,paddingHorizontal:12,marginTop:10,color:'#172033'},hint:{fontSize:13,color:'#7b8798',marginTop:7},row:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5eaf2',borderRadius:10,padding:16,marginTop:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},rowTitle:{fontSize:16,fontWeight:'700',color:'#344054'},save:{height:50,borderRadius:8,backgroundColor:'#2f7df6',alignItems:'center',justifyContent:'center',marginTop:18},saveText:{fontSize:16,fontWeight:'700',color:'#fff'}});
